spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/crm?characterEncoding=utf-8&useSSL=false
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

#项目路径
projectUrl:
  crm: http://127.0.0.0
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#日志配置
logging:
  pattern:
    console: "%d -%msg%n"
  file: "E:/logs/crm/crm.log"
  level: info


#因使用的为外置tomcat，这个设置无用，需要在外置的tomcat里设置
#server:
#  tomcat:
#    uri-encoding: UTF-8
