spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/crm?characterEncoding=utf-8&useSSL=false
#项目相关的配置
projectUrl:
  crm: http://127.0.0.0

logging:
  pattern:
    #  日志+内容+换行
    console: "%d -%msg%n"
  #默认的日志文件名称为spring.log
  file: "E:/logs/crm/crm.log"
  #日志的默认级别修改为info
  level: info